### ISSUE TITLE
Clicking on player to give achievement gives to one below.

### ISSUE THREAD

**Issue by QuantumBreed** [Handyfon/Farchievements#11]
I am unable to give the player at the top of the list any achievements as it gives it to the second instead. this does the same all the way down the list until the last person. clicking on them does not select anyone but moves to the top of the list.

**Comment by QuantumBreed** [comment]
issue results if there are more than one GM in game. GM-View is shown twice and problem above occurs.

**Comment by Handyfon** [comment]
fixed with 1.5.1
