### ISSUE TITLE
Achievement Categories & Points

### ISSUE THREAD

**Issue by msmyall88** [Handyfon/Farchievements#12]
Allows us to give a category to Achievements. Like for example a Combat category, Dice Roll category, and Roleplay category etc.

Then also give us an area to grant "_Points_" for achievements. Then each player can flex the number of points they have over another player.

Also another thought from my players, add an option to hover over achievements that are not unlocked a "Hint" text.

**Comment by Handyfon** [comment]
The new version will contain a scoreboard but no categories and hints as of yet.
