### ISSUE TITLE
Issue: Game Settings-Button not appearing

### ISSUE THREAD

**Issue by chicrozor** [Handyfon/Farchievements#2]
Module version 1.3.1
Foundry VTT version 0.8.8

As you can see even with option "Game Settings-Button" flagged, there is no button:
![image](https://user-images.githubusercontent.com/50779268/125660286-c3d4623a-9b4f-41c0-aca2-82fb4124a549.png)

Suggestion: Could it be possible to remove the d20 icon, so that the achievement icon replaces it?
![image](https://user-images.githubusercontent.com/50779268/125660480-aa2ef40c-da07-476f-abda-743fc06b82d3.png)

**Comment by brunocalado** [comment]
It's not showing for the players.

**Comment by Handyfon** [comment]
Oh it's actually below CUB, how interesting :D

Suggestion: Could it be possible to remove the d20 icon, so that the achievement icon replaces it?
can do!

**Comment by brunocalado** [comment]
There are to many modules that add buttons to the chat. Maybe could be easier sent the icon to the left bar or just let it on the config

**Comment by RevenantSeraph** [comment]
Achievements button does not appear at all for GM/Server view on the Game Settings tab, not even under Combat Utility Belt. Running Foundry 0.8.8 on Windows 10.
![image](https://user-images.githubusercontent.com/76813442/125839508-113ca548-1094-4f55-9eed-794e4d16d0aa.png)

I'm starting to think that as much as I like your module, it may not like me very much at all!

Also, on the subject of removing the d20 icon from the chat panel, is it possible to make that a toggleable option ? I don't mind having the extra icon there, personally, and would hate to lose the functionality of, say, the dice calculator from the Dice Tray module that winds up tied to that d20 icon.

**Comment by Handyfon** [comment]
Fixed in new version. The Icon now has a set position and no longer influences other parts of the chat.
