### ISSUE TITLE
Import/Export don't work anymore

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/Farchievements#20]
I can't import anymore. I received this message:

![image](https://user-images.githubusercontent.com/4999783/128200229-8d213429-d164-42f4-b43b-5e54ef243212.png)

**Comment by brunocalado** [comment]
I tried
- SWADE
- Tormenta 20

Foundry 8.8
Win 10
Chrome

**Comment by Pitchwife** [comment]
I have the same issue.

Firefox and Chrome, both
Foundry 0.8.8
DnD5e 1.4.1

**Comment by Handyfon** [comment]
The import/export has been reworked with the new data structure in version 10.1
