### ISSUE TITLE
Visual Bug: AlienRPG character sheet Skills tab not showing correctly when Farchievements module is enabled

### ISSUE THREAD

**Issue by TofuPotato** [Handyfon/Farchievements#23]
the sheet should look like this:
![image](https://user-images.githubusercontent.com/52269305/130889857-869b9187-32a9-448b-ae90-747b30eaad83.png)

But with Farchievements mod enabled, it overlaps like this:
![image](https://user-images.githubusercontent.com/52269305/130889936-8d8ac709-eb76-4c9d-9af6-bd18ebdab27e.png)

**Comment by Handyfon** [comment]
fixed in next update
