### ISSUE TITLE
Can't adjust who has an achievement

### ISSUE THREAD

**Issue by RinVindor** [Handyfon/Farchievements#24]
When I click on the name of a player it selects it but ALSO the one below that. Clicking on the same name removes it but doesn't remove the other one it highlighted.

**Comment by Boifuba** [comment]
Same issue here!

**Comment by busquinha** [comment]
also got it here, the module doesn't work at all :/

system: Tormenta 20
active modules:
Active Modules:
----------

- Ace library v1.2.0;
- Advanced Macros v1.9;
- Adventure Importer / Exporter v0.7.1;
- Adventure Music v1.1.0;
- Audio Folder v1.1;
- 💤 Away From Keyboard v1.0.0;
- Better Text Drawings v1.1.0.1;
- Bonus Die v1.0.1;
- Boss Bar v0.7.6;
- Cautious Gamemaster's Pack v0.3.1;
- Chat Images v2.5.3;
- Chat Portrait v0.5.10;
- Chat Reactions vThis is auto replaced;
- Combat Enhancements v1.0.2;
- Combat Focus v1.4.1;
- Combat Numbers v1.1.5;
- Compendium Browser T20 v0.4.5;
- Compendium Extra T20 v2.7.2;
- Compendium Folders v2.3.53;
- Confetti v1.0.5;
- Cursor Hider v1.2.1+0.8.8;
- DF Curvy Walls v3.2.1;
- DFreds Droppables v1.2.9;
- Dice So Nice! v4.1.4;
- Dice So Nice - Weighted Companion Cube Dice Set v1.0.2;
- Dice Tray v1.2.1;
- Domille's Wondrous Works - Battlemap Collection v1.2.1;
- Dr. Mapzo free maps (unofficial) v0.19.1;
- Dynamic Illumination v0.9.0;
- Ficha Loot T20 v1.2.1;
- Follow Me! v1.0.0;
- Forien's Quest Log v0.7.7;
- Foundry Achievements v1.5.1;
- Foundry Community Macros v0.46.0;
- Foundry Community Tables v0.17.0;
- FoundryVTT Mount Up! v3.1.5;
- Fudge v1.1.1;
- FXMaster v1.2.1;
- GM Notes v0.4.1;
- GM Screen v2.8.1;
- Health Estimate v2.6.9;
- Hey, Wait! v0.6.1;
- Illandril's Chat Enhancements v1.2.2;
- Initiative Double Click v1.1;
- Keikaku - To-Do List vv0.2.2;
- Less Fog v0.8.5;
- lib - Color Settings v2.8.0;
- Library: Chat Commands v1.3.3;
- Library: DF Hotkeys v2.3.5;
- libWrapper v1.10.5.0;
- Lichtgeschwindigkeit (Lightspeed) v1.4.4;
- Lordu's Custom Dice for Dice So Nice v0.33;
- Macro Folders v1.2.23;
- Maestro v0.7.5;
- Minimal UI v1.0.4;
- MiniMap v0.0.14;
- Monk's Little Details v1.0.37;
- Monk's TokenBar v1.0.51;
- Multiface Tiles v1.0.2;
- Multilevel Tokens v1.5.2;
- My Shared Compendia v1.0.0;
- Narrator Tools v0.61;
- Nice More Dice v1.0.3;
- PDFoundry v0.8.10;
- Permission Viewer v0.8.10;
- Pin Fixer v1.1.2;
- Pings v1.2.12+0.8.6;
- Playlist Importer v1.7.0;
- PnP - Pointer and Pings! v2.3.3;
- Polyglot v1.7.17;
- PopOut! v2.1;
- Quick Encounters v0.8.4;
- ✋ Raise My Hand v1.1.0;
- Roll From Compendium v1.1.2;
- Rolltable from sidebar v0.0.1;
- Sadness Chan v1.1.8;
- Settings Extender v1.1.6+0.8.6;
- Show Art v1.1.4;
- socketlib v1.0.9;
- SortableJS v1.10.2-fvtt1;
- SoundBoard by Blitz v1.5.2;
- SoundBoard Pack - Blitz Free Pack v1.0.0;
- SoundBoard Pack - Community v1.0.0;
- SoundFx Library v1.0.1;
- Soundscape v1.0.3;
- Split Journal v1.1;
- Theatre Inserts v1.20.2;
- The Furnace v2.6.1;
- The Rollsmith - Iridescent Rainbow Dice Set v1.0.0;
- Tidy UI - Game Settings v0.1.25;
- Timed Event v1.0.0;
- Token Attacher v4.1.2;
- Token Magic FX v0.5.2.1;
- TorchLight v0.10.0;
- TouchVTT v1.8.1;
- Trigger Happy v0.8.8;
- Turn Marker v2.8.1;
- Vehicles and Mechanisms v0.4.0;
- Whisper Box v1.1.1;
- Zoom/Pan Options v1.6.5;

**Comment by brunocalado** [comment]
same

**Comment by brunocalado** [comment]
https://user-images.githubusercontent.com/4999783/152364812-51cca8fe-1d32-413a-8e8d-20170a4b32bc.mp4

**Comment by Handyfon** [comment]
Should be fixed in Version 1.7.x
