### ISSUE TITLE
[BUG] Players getting errors

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/Farchievements#3]
Hi.

When players try to see their achievements they got this
![image](https://user-images.githubusercontent.com/4999783/125687707-52e7b0f2-4e57-4d3c-baee-d66e2ac9a3d7.png)

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/125690499-3112cc9a-3d09-4a92-83ce-b1dd5768ed5f.png)

**Comment by brunocalado** [comment]
After click in sync I got:
![image](https://user-images.githubusercontent.com/4999783/125692028-ec47c52d-449d-4046-bb16-4f85ffc2dd30.png)

**Comment by Handyfon** [comment]
Hey, can you provide me your foundry version as well as the system you are using?
Thanks in advance.

**Comment by brunocalado** [comment]
> Hey, can you provide me your foundry version as well as the system you are using?
> Thanks in advance.
Foundry VTT: 8.8
SWADE 19.5
Win 10
Chrome

**Comment by Handyfon** [comment]
Fixed in new version
