### ISSUE TITLE
Achievements are announced on every new game login

### ISSUE THREAD

**Issue by Z8MB1E** [Handyfon/Farchievements#31]
It seems that every time a player logs in to the game (for the first time that session), the achievement banner, chat message, and stinger play for achievements earned in previous sessions. Is there a way to prevent this from happening, and only show those things when an achievement is earned? Having it happen on every log in has frustrated my players a few times. 😝

**Comment by Handyfon** [comment]
Hey Z8MB1E, of you press the sync button that pops up down below when you give one or more a players an achievement, the animation(s) will play immidiately.
I could probalbly add an option to disable the animations when the players first load into the game.

**Comment by Z8MB1E** [comment]
> Hey Z8MB1E, of you press the sync button that pops up down below when you give one or more a players an achievement, the animation(s) will play immidiately. I could probalbly add an option to disable the animations when the players first load into the game.

Still think this is something you might add? My players get pretty annoyed each time it pops in with the fanfare and everything whenever they login. All of that is awesome at the moment I award my players an achievement, but not when they log in every time.

**Comment by Handyfon** [comment]
That seems to be a bug, can you provide some details on this behaviour, like for example if it replays all achievements the user has   or just some of them. Does it happen on every login or on every reload as well?

**Comment by Handyfon** [comment]
Should be fixed in 10.1
