### ISSUE TITLE
Suggestion: Achievement Progress

### ISSUE THREAD

**Issue by Gensokian** [Handyfon/Farchievements#32]
Having an achievement like "Observant Killer" which would require a player to use the enviroment 15 times to defeat an enemy is hard to track without notes; Would there be a possibility to add a progress tracker per achievement?

**Comment by kiloforce** [comment]
Love the idea!  Vote +1

**Comment by Handyfon** [comment]
Thanks for submitting this, I finally added it in version 12.0.
