### ISSUE TITLE
Bug with Alien RPG system

### ISSUE THREAD

**Issue by jacksands** [Handyfon/Farchievements#36]
I have found a strange Bug with Alien RPG system and Foundry achievements... 

the tab skills on the character sheet becomes misaligned and not functional... can you take a look pls?
![Screenshot_1](https://user-images.githubusercontent.com/7229143/173205455-4475db05-a1d3-4a63-ba22-6428a852a20c.png)
![Screenshot_2](https://user-images.githubusercontent.com/7229143/173205456-9ae41e36-0a68-4db8-9de9-fd257224096f.png)
![Screenshot_3](https://user-images.githubusercontent.com/7229143/173205457-0f24a725-912f-4d42-8e31-c6ea62d8ad13.png)

**Comment by Handyfon** [comment]
fixed in the next update :D
