### ISSUE TITLE
Display player's reward to everyone (enhancement)

### ISSUE THREAD

**Issue by davelacorneille** [Handyfon/Farchievements#39]
When you give an achievement to a certain player, all players should see that the player got it (more fun and stimulating for everyone).

At least put this as an option (like public achievement) if you don't want to change the actual behavior.

Also, in the scoreboard should display which achievements everyone got.

**Comment by kiloforce** [comment]
Yes please.  Vote +1

**Comment by Handyfon** [comment]
This is in the current version.

**Comment by davelacorneille** [comment]
Thank you!
