### ISSUE TITLE
Delete Achievement button does not work

### ISSUE THREAD

**Issue by RevenantSeraph** [Handyfon/Farchievements#4]
The Delete Achievement button does nothing. I tried this with no other modules active, and it still does nothing. Console spits out this error.
![image](https://user-images.githubusercontent.com/76813442/125720232-676fc822-b47b-469a-a858-7bf1f2279dd2.png)

**Comment by Handyfon** [comment]
Hey, can you provide me your foundry version as well as the system you are using?

**Comment by RevenantSeraph** [comment]
I'm running Foundry 0.8.8 on Windows 10 Home. Is that what you needed? Let me know if more info is required, I'll get you what I can.

**Comment by Handyfon** [comment]
Fixed in new version
