### ISSUE TITLE
[Suggestion] Allow for GM to reorder achievements

### ISSUE THREAD

**Issue by RevenantSeraph** [Handyfon/Farchievements#5]
Currently (unless I missed it!) there's no way to shift the order of achievements without deleting and reinputting everything - text, icon choice, etc. I'd love to see a way for the GM specifically to either click-and-drag to reorder, or have a text field on the edit screen that displays the achievement's number in the order and would allow you to change their ordering by changing the numbers. This would be convenient for people who want to organize their achievements into blocks of like types, but don't come up with the whole list at once.

**Comment by Pitchwife** [comment]
Yes please. Would use the export/import feature to get around this but import seems to be broken at the moment.

**Comment by Handyfon** [comment]
@RevenantSeraph Your suggestion has been added with version 10.1
