### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/Farchievements#53]
Hi. Just roll the dice is generating warns from this module.

![image](https://user-images.githubusercontent.com/4999783/208661887-1e709654-268a-4f29-8bea-08510158f8e4.png)

**Comment by Handyfon** [comment]
that issue seems to be on the other modules end as it checks chatmessages using a old data path.
Farchievements uses hidded chat messages to sync stuff between users and the gm
