### ISSUE TITLE
new achievements announced EVERY time players log in

### ISSUE THREAD

**Issue by wmve** [Handyfon/Farchievements#56]
my players love the idea of achievements but they are getting tired of listening to the music and seeing the announcement of ALL their achievements EVERY TIME they log in.  am i missing something, does one of the the settings turn that off so they can just go check the list when they want?  (none of them seem obvious to me) it's getting to the point that we're looking at turning it off.  i'm on foundry v9.280 still.  using 3.5e 1.0.6.

players are using both firefox and chrome.  most are not using private mode, but i do so in testing sometimes.  but it happens when NOT in private mode as well.

**Comment by Handyfon** [comment]
Added the option in the new version
