### ISSUE TITLE
farchievements is using old flat core compatibility fields

### ISSUE THREAD

**Issue by orangepeelbeef** [Handyfon/Farchievements#60]
old compatibility fields
<img width="756" alt="image" src="https://github.com/Handyfon/Farchievements/assets/130179/cc3dbaa3-5bfd-42dc-ac71-8d178a04f443">

new compat field is like
  `"compatibility": {
    "minimum": "10",
    "verified": "11"
  },`

**Comment by Handyfon** [comment]
Thanks, fixed in the new version
