### ISSUE TITLE
Scoreboard no longer shows

### ISSUE THREAD

**Issue by DMSavian** [Handyfon/Farchievements#63]
The scoreboard tab no longer shows the scores. I have tried playing with all the settings, looking from other accounts, refreshed it, nothing has worked. I don't know if it bugged out or if I am missing something. 
![image](https://github.com/Handyfon/Farchievements/assets/128620434/34d2ad3a-5c34-486f-807e-63a53c450595)

**Comment by DMSavian** [comment]
Okay, so something is definitely wrong. It won't show any of my player's achievements anymore, even though they are marked as having them.

**Comment by PandaDesBois** [comment]
I agree, it won't show achievement of my player + if my player click on the edit mode, they see all the achievement hidden or not :/

**Comment by DMSavian** [comment]
I have now found out that my players can't see any of their personal achievements either. They also can see all of the achievements even if they are hidden.

**Comment by Handyfon** [comment]
Fixed in new version
