### ISSUE TITLE
Achievements chat button placement

### ISSUE THREAD

**Issue by fiagewinnt** [Handyfon/Farchievements#7]
Hi! After updating to version 1.4.6 the button placement for the chat button got kind of jumbled. 
The two other buttons are from MyTab and Dice Tray. Before the update the achievements button was placed to the left of the two and fit just nicely.

![image](https://user-images.githubusercontent.com/61601634/126078227-6f38443d-1f7c-4e2b-abdd-4d2152fb2828.png)

**Comment by Handyfon** [comment]
Fixed 👍
