### ISSUE TITLE
Last Player in List not shown

### ISSUE THREAD

**Issue by Berytak** [Handyfon/Farchievements#8]
Last Player in Playerlist is not shown in the achivement user selection list.

Last player I added is Player8.
![image](https://user-images.githubusercontent.com/85394657/126135983-5d7507ce-dcc5-49b1-a139-2722e8be6f82.png)

Scrollbar is at the bottom and the last user is Hans and noch Player8.
![image](https://user-images.githubusercontent.com/85394657/126136175-f556e467-ff89-4e39-9b52-8ac17ac9ccb0.png)

**Comment by Handyfon** [comment]
Pushed a fix, please tell me if the issue persists

**Comment by Berytak** [comment]
The problem ist fixed!
Thank you, I apprechiate your quick response.
